server:
  port: 9001

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bank?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true

# 令牌自定义标识
token:
  header: authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# 图片存储地址
file:
  imgPath: C:\\Users\\world\\Desktop\\题库管理系统\\img\\